use_frameworks!

platform :ios, '9.0'

target 'AlamofireImageKit_Example' do
  pod 'AlamofireImageKit', :path => '../'

  target 'AlamofireImageKit_Tests' do
    inherit! :search_paths

    
  end
end
